### ISSUE TITLE
Missing the information in About field.

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure.zh-cn#25]
Missing the information in "About" field.

Missing the Link to "Github Pages"

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
not loclization issue

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/180975900-bbc58b5d-366b-441b-a269-d07f09b0d8c3.png)
