### ISSUE TITLE
Student + LAK Instructions documents have a Note with leading spaces, leading to undesired rendering.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure.zh-cn#27]
This line, in the starting section of all student + LAK lab instructions appears to have ~16 additional/unneeded spaces:

                **注意：** 我们提供 **[交互式实验室模拟](https://mslabs.cloudguides.com/guides/AZ-800%20Lab%20Simulation%20-%20Implementing%20identity%20services%20and%20Group%20Policy)** ，让你能以自己的节奏点击浏览实验室。 你可能会发现交互式模拟与托管实验室之间存在细微差异，但演示的核心概念和思想是相同的。

This leads to undesirable display in both Github and ALH rendering.

If one removes the leading spaces, it displays as expected:

![image](https://user-images.githubusercontent.com/49700217/228992180-cc81b7fa-9177-406b-9d70-c54743250346.png)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Updates made to [Locfiles ](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEFzc2V0IElEO1N0YXJ0cyBXaXRoO0xBQl9BSzwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtDaGluZXNlIChTaW1wbGlmaWVkKTwvUVI%2bPFFSIElkPSI0IiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEFzc2V0IElEO0NvbnRhaW5zOy5tZDwvUVI%2bPFFSIElkPSI1IiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgR3JvdXA7Q29udGFpbnM7QVotODAwPC9RUj48UVIgSWQ9IjYiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgRmlsZSBSZWZlcmVuY2U7Q29udGFpbnM7NTAzMzQ8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d)
